"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype on
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  let g:vundles=['general', 'programming', 'php', 'ruby', 'python', 'javascript', 'html', 'misc']
  "let g:vundles=['general']
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  "Bundle 'L9'
  "Bundle 'FuzzyFinder'
endif

" Extra neosnippets to override/extend defaults
let g:neosnippet#snippets_directory='~/.vim/snippets'

" Colors
set t_Co=256

" FuzzyFinder config
"
" ,f opens fuzzy finder file
map <leader>f :FufFile<CR>

" <Ctrl+\> Open tag definition in new tab
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>
" <Alt+]> Open tag definition in new vertical split
map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

" Source any local config not in dotfiles (like I have to use tabs at work)
" This needs to be somewhere in your vim path - ~/.vim is a good idea.
runtime vimrc.local

